mysql:
  host: 127.0.0.1
  port: 3306
  username: mysqladmin
  password: mysqlpassword
  dbname: medialib_db

minio:
  host: 127.0.0.1
  port: 9000
  username: minioadmin
  password: miniopassword
  bucket_name: media-lib
  public_endpoint: 127.0.0.1:9000
