postgres:
  host: 10.9.22.11
  port: 5432
  username: postgresadmin
  password: postgrespassword
  dbname: medialib_db

minio:
  host: 127.0.0.1
  port: 9000
  username: minioadmin
  password: miniopassword
  bucket_name: media-lib
  public_endpoint: 10.9.22.15:9000
