server:
  log_level: debug # debug | info | warn | error
  secret_key: gboUV8ZUszxKNqdGMy0J51KLZDDo4uXR
  work_path: /data
  users:
    - name: user1
      password: user1
  video_tags: ["SM", "OL"]

postgres:
  host: 127.0.0.1
  port: 5432
  username: postgresadmin
  password: postgrespassword
  dbname: testdb

minio:
  host: 127.0.0.1
  port: 9000
  username: minioadmin
  password: miniopassword
  bucket_name: media-lib
  public_endpoint: 127.0.0.1:9000
