mysql:
  host: 127.0.0.1
  port: 3306
  username: mysqladmin
  password: mysqlpassword
  dbname: media_lib

minio:
  endpoint: 127.0.0.1:9000
  username: minioadmin
  password: miniopassword
  bucketName: media-lib
