server:
  log_level: debug # debug | info | warn | error
  video_tags: ["女教师", "OL"]

postgres:
  host: 127.0.0.1
  port: 5432
  username: postgresadmin
  password: postgrespassword
  dbname: testdb

minio:
  host: 127.0.0.1
  port: 9000
  username: minioadmin
  password: miniopassword
  bucket_name: media-lib
  public_endpoint: 127.0.0.1:9000
