server:
  log_level: warn # debug | info | warn | error

postgres:
  host: host.docker.internal
  port: 5432
  username: medialibadmin
  password: medialibpassword
  dbname: medialib_db

minio:
  host: host.docker.internal
  port: 9000
  username: minioadmin
  password: miniopassword
  bucket_name: media-lib
  public_endpoint: 127.0.0.1:9000
