mysql:
  host: host.docker.internal
  port: 3306
  username: mysqladmin
  password: mysqlpassword
  dbname: media_lib

minio:
  host: host.docker.internal
  port: 9000
  username: minioadmin
  password: miniopassword
  bucket_name: media-lib
  public_endpoint: 127.0.0.1:9000
